version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file: xx.env
    ports:
      - '8000:8000'
    tty: true
    depends_on:
      - db
    volumes:
      - $PWD:/app
  db:
    image: postgres:15.1
    container_name: db
    hostname: db
    environment:
      - POSTGRES_USER=xx
      - POSTGRES_PASSWORD=xx
      - POSTGRES_DB=xx
    ports:
      - '5432:5432'
